### ISSUE TITLE
Club schedule: chronological order or reverse?

### ISSUE THREAD

**Issue by liyishuai** [euisuny/plclub-web#3]
Are we emphasizing "next upcoming talk" or "past talks"?

**Comment by dunnl** [comment]
At the moment it seems to be reverse order, "next talk first." The wording says "Fall 2019 Schedule" which would make me think it would be chronological order.

Since we don't have a full schedule in advance, I think reverse chronological order makes sense so we can shine a spotlight on whatever's coming up. But if we keep it, we could change it to something like:
```
Upcoming talk:
<talk date>
<talk abstract>

Past talks:
<talk title>
<talk title>
<talk title>
```
